apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - name: aws
    image: tfenn/awscli:1.0
    imagePullPolicy: Always
    command:
    - sleep
    args:
    - infinity
    tty: true
  - name: ansible
    image: tfenn/ansiblecli:1.0
    imagePullPolicy: Always
    command:
    - sleep
    args:
    - infinity
    tty: true