# all-playbooks to config LB and App Servers

---
  - import_playbook: yum-update.yml
  - import_playbook: install-services.yml
  - import_playbook: setup-app.yml
  - import_playbook: setup-lb.yml
  - import_playbook: check-status.yml