---
  - hosts: loadbalancers
    tasks:
    - name: copy config file
      copy: src=/config.cfg dest=/etc/config.cfg

  - hosts: webservers
    tasks: 
    - name: Sync folders
      synchronize: src=./app dest=/var/www/html/app